version: "3.9"

services:
  web:
    build: .
    image: velizar86/join-backend:latest
    pull_policy: always
    env_file: [.env]
    command: ["web"]                  # entrypoint.sh web
    expose:
      - "8000"
    volumes:
      - static_data:/static
      - media_data:/media
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on: [web]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_data:/static:ro
      - media_data:/media:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    # Пускай я one-off за издаване/renew (виж стъпките по-долу)
    entrypoint: /bin/sh
    command: -c "echo Certbot helper"

volumes:
  static_data:
  media_data:
